In [2]:
import numpy as np
import pandas as pd
import sys
import os
sys.path.append('../src')
sys.path.append('../data')
import  semantic_analysis

c:\Users\inest\AppData\Local\Programs\Python\Python310\lib\site-packages\tqdm\auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm


In [3]:
# Define the path
base_path = r"C:\Users\inest\OneDrive - Danmarks Tekniske Universitet\Semester I\Computational Tools for Data Science\data"

# Loop through years from 2014 to 2019
for year in range(2016, 2020):

    file_path = os.path.join(base_path, f"reuters_2019_output.csv")
    
    # Check if the file exists for the given year
    if os.path.exists(file_path):
        # Read the CSV file
        #semantic_analysis.lexicon_nltk(file_path)
        output = semantic_analysis.roberta_semantic_algorithm_twitter(file_path)
        
        print(f"File saved for year {year}")
    else:
        print(f"No file found for year {year}")


Truncation was not explicitly activated but `max_length` is provided a specific value, please use `truncation=True` to explicitly truncate examples to max length. Defaulting to 'longest_first' truncation strategy. If you encode pairs of sequences (GLUE-style) with the tokenizer you can select this strategy more precisely by providing a specific strategy to `truncation`.


KeyboardInterrupt: 

In [ ]:
# Define the path
base_path = r"C:\Users\storr\OneDrive - Danmarks Tekniske Universitet\Year 1\Semester 1\Computational Tools for Data Science\Project\DATA"

# Loop through years from 2014 to 2019
for year in range(2014, 2020):

    file_path = os.path.join(base_path, f"cnn_{year}_output.csv")
    
    # Check if the file exists for the given year
    if os.path.exists(file_path):
        # Read the CSV file
        #semantic_analysis.lexicon_nltk(file_path)
        output_twitter = semantic_analysis.roberta_semantic_algorithm_twitter(file_path)
        
        print(f"File saved for year {year}")
    else:
        print(f"No file found for year {year}")

tensor([[ 0.1195, -0.1077]], grad_fn=<AddmmBackward0>)
tensor([ 0.1195, -0.1077], grad_fn=<SelectBackward0>)
<class 'torch.Tensor'>
tensor([ 0.1195, -0.1077], grad_fn=<SelectBackward0>)
