In [1]:
import numpy as np
import pandas as pd
import sys
import os
sys.path.append('../src')
sys.path.append('../data')
import  semantic_analysis

In [4]:
# Define the path
base_path = r"C:\Users\storr\OneDrive - Danmarks Tekniske Universitet\Year 1\Semester 1\Computational Tools for Data Science\Project\DATA"

# Loop through years from 2014 to 2019
for year in range(2014, 2020):

    file_path = os.path.join(base_path, f"cnn_{year}_output.csv")
    
    # Check if the file exists for the given year
    if os.path.exists(file_path):
        # Read the CSV file
        #semantic_analysis.lexicon_nltk(file_path)
        output = semantic_analysis.roberta_semantic_algorithm_news(file_path)
        
        print(f"File saved for year {year}")
    else:
        print(f"No file found for year {year}")


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at fhamborg/roberta-targeted-sentiment-classification-newsarticles and are newly initialized: ['encoder.layer.0.intermediate.dense.bias', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerN

[0.5731408 0.4268592]
[0.56898683 0.43101317]
[0.5685259  0.43147406]
[0.56615585 0.43384418]
[0.56635475 0.43364525]
File saved for year 2014


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at fhamborg/roberta-targeted-sentiment-classification-newsarticles and are newly initialized: ['encoder.layer.0.intermediate.dense.bias', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerN

[0.38582787 0.61417216]
[0.38706586 0.6129341 ]
[0.3863192  0.61368084]
[0.39038104 0.60961896]
[0.38680845 0.6131916 ]
File saved for year 2015


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at fhamborg/roberta-targeted-sentiment-classification-newsarticles and are newly initialized: ['encoder.layer.0.intermediate.dense.bias', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerN

[0.36050007 0.6394999 ]
[0.36112934 0.63887066]
[0.362389   0.63761103]
[0.36154032 0.6384597 ]
[0.35877016 0.6412298 ]
File saved for year 2016


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at fhamborg/roberta-targeted-sentiment-classification-newsarticles and are newly initialized: ['encoder.layer.0.intermediate.dense.bias', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerN

[0.33073235 0.6692677 ]
[0.3351261  0.66487396]
[0.33385405 0.6661459 ]
[0.33389157 0.66610837]
[0.3348793  0.66512066]
File saved for year 2017


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at fhamborg/roberta-targeted-sentiment-classification-newsarticles and are newly initialized: ['encoder.layer.0.intermediate.dense.bias', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerN

[0.42349154 0.57650846]
[0.42956316 0.57043684]
[0.42165902 0.57834095]
[0.41876978 0.5812302 ]
[0.4247753 0.5752247]
File saved for year 2018


Some weights of RobertaForSequenceClassification were not initialized from the model checkpoint at fhamborg/roberta-targeted-sentiment-classification-newsarticles and are newly initialized: ['encoder.layer.0.intermediate.dense.bias', 'encoder.layer.11.attention.output.dense.bias', 'encoder.layer.2.attention.self.query.weight', 'encoder.layer.5.attention.self.value.weight', 'encoder.layer.1.attention.output.LayerNorm.weight', 'encoder.layer.5.attention.self.key.weight', 'encoder.layer.2.attention.output.LayerNorm.bias', 'encoder.layer.8.output.LayerNorm.weight', 'encoder.layer.9.attention.output.dense.weight', 'encoder.layer.7.output.dense.bias', 'encoder.layer.3.output.dense.bias', 'encoder.layer.1.attention.self.key.bias', 'encoder.layer.0.intermediate.dense.weight', 'encoder.layer.10.intermediate.dense.weight', 'encoder.layer.9.output.dense.weight', 'encoder.layer.1.attention.self.query.bias', 'encoder.layer.7.attention.output.LayerNorm.bias', 'encoder.layer.1.attention.output.LayerN

[0.52215534 0.4778447 ]
[0.5037684 0.4962316]
[0.5056984  0.49430162]
[0.5145188 0.4854812]
[0.50611234 0.49388766]
File saved for year 2019


In [ ]:
# Define the path
base_path = r"C:\Users\storr\OneDrive - Danmarks Tekniske Universitet\Year 1\Semester 1\Computational Tools for Data Science\Project\DATA"

# Loop through years from 2014 to 2019
for year in range(2014, 2020):

    file_path = os.path.join(base_path, f"cnn_{year}_output.csv")
    
    # Check if the file exists for the given year
    if os.path.exists(file_path):
        # Read the CSV file
        #semantic_analysis.lexicon_nltk(file_path)
        output_twitter = semantic_analysis.roberta_semantic_algorithm_twitter(file_path)
        
        print(f"File saved for year {year}")
    else:
        print(f"No file found for year {year}")

tensor([[ 0.1195, -0.1077]], grad_fn=<AddmmBackward0>)
tensor([ 0.1195, -0.1077], grad_fn=<SelectBackward0>)
<class 'torch.Tensor'>
tensor([ 0.1195, -0.1077], grad_fn=<SelectBackward0>)
